# Generated by Django 4.2.3 on 2023-07-20 20:49

from django.db import migrations, models
import jobbox.job.validators


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_job_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='companies_logo', validators=[jobbox.job.validators.FileSizeValidatorInMB(1)]),
        ),
    ]
