# Generated by Django 4.2.3 on 2023-07-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_uploadcv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadcv',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
