# Generated by Django 4.2.3 on 2023-07-29 10:27

from django.db import migrations, models
import jobbox.job.validators


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_alter_uploadcv_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadcv',
            name='pdf_file',
            field=models.FileField(upload_to='cv_pdfs', validators=[jobbox.job.validators.FileSizeValidatorInMB(2), jobbox.job.validators.validate_pdf_file]),
        ),
    ]
