# Generated by Django 4.2.3 on 2023-07-24 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hrtask',
            options={'ordering': ['pk']},
        ),
        migrations.RemoveField(
            model_name='hrtask',
            name='target_date',
        ),
    ]
