# Generated by Django 4.2.3 on 2023-07-29 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_hrtask_options_remove_hrtask_target_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hrtask',
            options={'ordering': ['pk'], 'verbose_name': 'HR Task', 'verbose_name_plural': 'HR Tasks'},
        ),
    ]
