# Generated by Django 4.2.3 on 2023-07-26 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_contactus_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
