# Generated by Django 4.2.3 on 2023-07-27 16:20

import django.core.validators
from django.db import migrations, models
import jobbox.common.validators
import jobbox.job.validators


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilehr',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[jobbox.common.validators.check_if_only_letters]),
        ),
        migrations.AddField(
            model_name='profilehr',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profilehr', validators=[jobbox.job.validators.FileSizeValidatorInMB(1)]),
        ),
        migrations.AddField(
            model_name='profilehr',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.MinLengthValidator(4), jobbox.common.validators.check_if_number_starts_with_zero_or_plus]),
        ),
        migrations.AlterField(
            model_name='profilehr',
            name='company_name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profilehr',
            name='first_name',
            field=models.CharField(default='Null', max_length=30, validators=[jobbox.common.validators.check_if_only_letters]),
            preserve_default=False,
        ),
    ]
