# Generated by Django 4.2.3 on 2023-07-27 16:24

from django.db import migrations, models
import jobbox.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_profilehr_last_name_profilehr_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilehr',
            name='first_name',
            field=models.CharField(max_length=30, null=True, validators=[jobbox.common.validators.check_if_only_letters]),
        ),
    ]
