# Generated by Django 4.2.3 on 2023-07-29 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_profilehr_first_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'Contact Us'},
        ),
        migrations.AlterModelOptions(
            name='profilehr',
            options={'verbose_name_plural': 'Profile HRs'},
        ),
    ]
