# Generated by Django 4.2.3 on 2023-08-05 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_contactus_options_alter_profilehr_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='description',
            field=models.TextField(max_length=150, validators=[django.core.validators.MinLengthValidator(20)]),
        ),
    ]
